;; GENERATED by testdata/gen_vectors.cljs — do not edit by hand.
;; PieceCIDs from @filoz/synapse-core/piece; selectors from viem's
;; toFunctionSelector; addresses from @filoz/synapse-core/chains.
;; None of these come from this library.
(ns filecoin.cloud.vectors)

(def pieces
 [
  {:size 1
   :cid "bafkzcibcpybhd4x4tlw5236625rntv7ck64vlvmrbsaf52jktye6ziyg6r3fsia"
   :height 2
   :padding 126
   :padded-size 128
   :root "0x71f2fc9aeddd6fded762d9d7e257b955d5910c805ee92a9e09eca306f4765920"}
  {:size 2
   :cid "bafkzcibcpubeqxprjjmmiahy2f2t5t2wac6nb2gmwxfyoeww44lge4fvgpyfagi"
   :height 2
   :padding 125
   :padded-size 128
   :root "0x485df14a58c400f8d1753ecf5600bcd0e8ccb5cb8712d6e7166270b533f05019"}
  {:size 32
   :cid "bafkzcibcl4bkdt7yoltybpjyfdfelknj46gxpzynfhm3g7fpwun7rivktgjralq"
   :height 2
   :padding 95
   :padded-size 128
   :root "0xa1cff872e780bd3828ca45a9a9e78d77e70d29d9b37cafb51bf8a2aa9993102e"}
  {:size 64
   :cid "bafkzcibch4bddywexxqpjbiyqiz4jeoexjus2miicaego5kvo4h3gkof7jbgepi"
   :height 2
   :padding 63
   :padded-size 128
   :root "0x31e2c4bde0f485188233c491c4ba692d31081008677555770fb329c5fa42623d"}
  {:size 65
   :cid "bafkzcibchybikldq7ylz7s5vwpb6zwcx6oswb3rj62roqzivjedmx7sefwytqia"
   :height 2
   :padding 62
   :padded-size 128
   :root "0x852c70fe179fcbb5b3c3ecd857f3a560ee29f6a2e865154906cbfe442db13820"}
  {:size 66
   :cid "bafkzcibchuboe7o3vmrshz36qhjxz657fxxvtyfwsguevqisvt7pypu7b2hjaoq"
   :height 2
   :padding 61
   :padded-size 128
   :root "0xe27ddbab2323e77e81d37cfbbf2def59e0b691a84ac112acfefc3e9f0e8e903a"}
  {:size 100
   :cid "bafkzcibcdmbmhxp7o3q5ntjp4triphpezgi4gaonnueaqnvfzmeohbk3atjlcpy"
   :height 2
   :padding 27
   :padded-size 128
   :root "0xc3ddff76e1d6cd2fe4e2879de4c991c301cd6d080836a5cb08e3855b04d2b13f"}
  {:size 126
   :cid "bafkzcibcaebpnonkdsiuncrylytcnrdu54lb2eiehoclxg7gzrimcwzinnermey"
   :height 2
   :padding 1
   :padded-size 128
   :root "0xf6b9aa1c91468a385e2626c474ef161d11043b84bb9be6cc50c15b286b491613"}
  {:size 127
   :cid "bafkzcibcaabeog5fgfyz2dt3sie26yu4wjtupnpx3ouo6rxksyxnmvhqpd3umhy"
   :height 2
   :padding 0
   :padded-size 128
   :root "0x471ba531719d0e7b9209af629cb26747b5f7dba8ef46ea962ed654f078f7461f"}
  {:size 128
   :cid "bafkzcibcpybu4kmaf3ojcbemv5l7uauscl22k4rwx2whositxld23j6cxjydyea"
   :height 3
   :padding 126
   :padded-size 256
   :root "0x4e29802edc91048caf57fa029212f5a57236beac774913bac7ada7c2ba703c10"}
  {:size 129
   :cid "bafkzcibcpub2qlokm6xohzlpcliefzu5kpmdc55v3nzp56r2shc24nzakxlcmpi"
   :height 3
   :padding 125
   :padded-size 256
   :root "0xa82dca67aee3e56f12d042e69d53d83177b5db72fefa3a91c5ae372055d6263d"}
  {:size 254
   :cid "bafkzcibcaab5q36nb4uco62hqpcr6qlr6fwdwoxeqdh235raegjyzyne7ac5sgi"
   :height 3
   :padding 0
   :padded-size 256
   :root "0xd86fcd0f28277b4783c51f4171f16c3b3ae480cfadf62021938ce1a4f805d919"}
  {:size 255
   :cid "bafkzcibd7uaqitln5hcc5wf4ixegeweqjtmcz7mbwsj4bsp2bvrwofjvcz5dxxyh"
   :height 4
   :padding 253
   :padded-size 512
   :root "0x4d6de9c42ed8bc45c86258904cd82cfd81b493c0c9fa0d63671535167a3bdf07"}
  {:size 256
   :cid "bafkzcibd7qaqjhjuo6xyrn5kx63htnkweqgejqoaewm7pabnhhswc4bzcpj7ifqp"
   :height 4
   :padding 252
   :padded-size 512
   :root "0x9d3477af88b7aabfb679b556240c44c1c02599f7802d39e561703913d3f4160f"}
  {:size 257
   :cid "bafkzcibd7maqiy3jkfr7oi5fmlllngbem4ixdo7nrqrvpuvnwn47n55afmbmd2rv"
   :height 4
   :padding 251
   :padded-size 512
   :root "0x63695163f723a562d6b69824671171bbed8c2357d2adb379f6f7a02b02c1ea35"}
  {:size 508
   :cid "bafkzcibcaackres2welyr7hwoera5hvbnghthg74bh332cslzecfmnak42g5efi"
   :height 4
   :padding 0
   :padded-size 512
   :root "0xa8925ab11788fcf671220e9ea1698f339bfc09f7bd0a4bc90456340ae68dd215"}
  {:size 1000
   :cid "bafkzcibccacsgghnx4qtuojxbxhjtsoslin3xsktkybcx47dj7oywwnpcd7ukna"
   :height 5
   :padding 16
   :padded-size 1024
   :root "0x2318edbf213a39370dce99c9d25a1bbbc95356022bf3e34fdd8b59af10ff4534"}
  {:size 1016
   :cid "bafkzcibcaac3bsqctynrlr7covqzv2moqtdu7tjicvnis6edswskqdkeowgakoi"
   :height 5
   :padding 0
   :padded-size 1024
   :root "0xb0ca029e1b15c7e275619ae98e84c74fcd28155a89788395a4a80d44758c0539"}
  {:size 1017
   :cid "bafkzcibd64dqndgccvtyie2373ckzv66ofgbwcd3qsuuiix5zrmvheqsy436yobc"
   :height 6
   :padding 1015
   :padded-size 2048
   :root "0x8cc2156784135bfec4acd7de714c1b087b84a94422fdcc59539212c737ec3822"}
  {:size 4096
   :cid "bafkzcibdyapqq2z43imecl6rzhmt7p7urukessi5km6u5pi5uovvoam3nxwls5yo"
   :height 8
   :padding 4032
   :padded-size 8192
   :root "0x6b3cda18412fd1c9d93fbff48d1449491d533d4ebd1da3ab57019b6decb9770e"}
 ])

;; Every function in every deployed ABI, with the selector viem
;; derives from its canonical signature. The library's constants
;; are checked against this, so a mistyped signature is a missing
;; entry rather than four plausible wrong bytes.
(def selectors
 [
  {:contract "pdp" :signature "FIL_CLEANUP_DEPOSIT()" :selector "0x56cba7ea"}
  {:contract "pdp" :signature "INACTIVITY_WINDOW()" :selector "0x03ac08f6"}
  {:contract "pdp" :signature "LEGACY_ACTIVITY_EPOCH()" :selector "0x482c1628"}
  {:contract "pdp" :signature "MAX_ENQUEUED_REMOVALS()" :selector "0x9f8cb3bd"}
  {:contract "pdp" :signature "MAX_PIECE_SIZE_LOG2()" :selector "0xf8eb8276"}
  {:contract "pdp" :signature "UPGRADE_INTERFACE_VERSION()" :selector "0xad3cb1cc"}
  {:contract "pdp" :signature "VERSION()" :selector "0xffa1ad74"}
  {:contract "pdp" :signature "addPieces(uint256,address,(bytes)[],bytes)" :selector "0x9afd37f2"}
  {:contract "pdp" :signature "announcePlannedUpgrade((address,uint96))" :selector "0xbd003827"}
  {:contract "pdp" :signature "calculateProofFee(uint256)" :selector "0x86981308"}
  {:contract "pdp" :signature "calculateProofFeeForSize(uint256)" :selector "0xe9a31a55"}
  {:contract "pdp" :signature "claimDataSetStorageProvider(uint256,bytes)" :selector "0xdf0f3248"}
  {:contract "pdp" :signature "cleanupPieces(uint256,uint256)" :selector "0xb24b2241"}
  {:contract "pdp" :signature "createDataSet(address,bytes)" :selector "0xbbae41cb"}
  {:contract "pdp" :signature "dataSetLive(uint256)" :selector "0xca759f27"}
  {:contract "pdp" :signature "deleteDataSet(uint256,bytes)" :selector "0x7a1e2990"}
  {:contract "pdp" :signature "feeEffectiveTime()" :selector "0x996ad96a"}
  {:contract "pdp" :signature "feePerTiB()" :selector "0x22ef3f73"}
  {:contract "pdp" :signature "findPieceIds(uint256,uint256[])" :selector "0x349c9179"}
  {:contract "pdp" :signature "findPieceIdsByCid(uint256,(bytes),uint256,uint256)" :selector "0x6a4991a1"}
  {:contract "pdp" :signature "getActivePieceCount(uint256)" :selector "0x5353bdfd"}
  {:contract "pdp" :signature "getActivePieces(uint256,uint256,uint256)" :selector "0x39f51544"}
  {:contract "pdp" :signature "getActivePiecesByCursor(uint256,uint256,uint256)" :selector "0x9fbc9f1b"}
  {:contract "pdp" :signature "getChallengeFinality()" :selector "0xf83758fe"}
  {:contract "pdp" :signature "getChallengeRange(uint256)" :selector "0x89208ba9"}
  {:contract "pdp" :signature "getDataSetLastProvenEpoch(uint256)" :selector "0x04595c1a"}
  {:contract "pdp" :signature "getDataSetLeafCount(uint256)" :selector "0xa531998c"}
  {:contract "pdp" :signature "getDataSetListener(uint256)" :selector "0x2b3129bb"}
  {:contract "pdp" :signature "getDataSetStorageProvider(uint256)" :selector "0x21b7cd1c"}
  {:contract "pdp" :signature "getNextChallengeEpoch(uint256)" :selector "0x6ba4608f"}
  {:contract "pdp" :signature "getNextDataSetId()" :selector "0x442cded3"}
  {:contract "pdp" :signature "getNextPieceId(uint256)" :selector "0x1c5ae80f"}
  {:contract "pdp" :signature "getPieceCid(uint256,uint256)" :selector "0x25bbbedf"}
  {:contract "pdp" :signature "getPieceLeafCount(uint256,uint256)" :selector "0x0cd7b880"}
  {:contract "pdp" :signature "getRandomness(uint256)" :selector "0x453f4f62"}
  {:contract "pdp" :signature "getScheduledRemovals(uint256)" :selector "0x6fa44692"}
  {:contract "pdp" :signature "initialize()" :selector "0x8129fc1c"}
  {:contract "pdp" :signature "migrate()" :selector "0x8fd3ab80"}
  {:contract "pdp" :signature "nextProvingPeriod(uint256,uint256,bytes)" :selector "0x45c0b92d"}
  {:contract "pdp" :signature "nextUpgrade()" :selector "0x315e49ea"}
  {:contract "pdp" :signature "owner()" :selector "0x8da5cb5b"}
  {:contract "pdp" :signature "pieceChallengable(uint256,uint256)" :selector "0xdc635266"}
  {:contract "pdp" :signature "pieceLive(uint256,uint256)" :selector "0x1a271225"}
  {:contract "pdp" :signature "proposeDataSetStorageProvider(uint256,address)" :selector "0x43186080"}
  {:contract "pdp" :signature "proposedFeePerTiB()" :selector "0xba74d94c"}
  {:contract "pdp" :signature "provePossession(uint256,(bytes32,bytes32[])[])" :selector "0xf58f952b"}
  {:contract "pdp" :signature "proxiableUUID()" :selector "0x52d1902d"}
  {:contract "pdp" :signature "renounceOwnership()" :selector "0x715018a6"}
  {:contract "pdp" :signature "schedulePieceDeletions(uint256,uint256[],bytes)" :selector "0x0c292024"}
  {:contract "pdp" :signature "transferOwnership(address)" :selector "0xf2fde38b"}
  {:contract "pdp" :signature "updateProofFee(uint256)" :selector "0x46bf7ed3"}
  {:contract "pdp" :signature "upgradeToAndCall(address,bytes)" :selector "0x4f1ef286"}
  {:contract "filecoinPay" :signature "COMMISSION_MAX_BPS()" :selector "0x8aab236a"}
  {:contract "filecoinPay" :signature "NETWORK_FEE_DENOMINATOR()" :selector "0xe0975cf8"}
  {:contract "filecoinPay" :signature "NETWORK_FEE_NUMERATOR()" :selector "0x553d8c82"}
  {:contract "filecoinPay" :signature "accounts(address,address)" :selector "0xad74b775"}
  {:contract "filecoinPay" :signature "auctionInfo(address)" :selector "0x0448e51a"}
  {:contract "filecoinPay" :signature "burnForFees(address,address,uint256)" :selector "0x1a257300"}
  {:contract "filecoinPay" :signature "createRail(address,address,address,address,uint256,address)" :selector "0xf9f78de8"}
  {:contract "filecoinPay" :signature "deposit(address,address,uint256)" :selector "0x8340f549"}
  {:contract "filecoinPay" :signature "depositWithAuthorization(address,address,uint256,uint256,uint256,bytes32,uint8,bytes32,bytes32)" :selector "0x8a94d4fc"}
  {:contract "filecoinPay" :signature "depositWithAuthorizationAndApproveOperator(address,address,uint256,uint256,uint256,bytes32,uint8,bytes32,bytes32,address,uint256,uint256,uint256)" :selector "0x18ccb209"}
  {:contract "filecoinPay" :signature "depositWithAuthorizationAndIncreaseOperatorApproval(address,address,uint256,uint256,uint256,bytes32,uint8,bytes32,bytes32,address,uint256,uint256)" :selector "0xdcaad80b"}
  {:contract "filecoinPay" :signature "depositWithPermit(address,address,uint256,uint256,uint8,bytes32,bytes32)" :selector "0x8ef59739"}
  {:contract "filecoinPay" :signature "depositWithPermitAndApproveOperator(address,address,uint256,uint256,uint8,bytes32,bytes32,address,uint256,uint256,uint256)" :selector "0x7218b707"}
  {:contract "filecoinPay" :signature "depositWithPermitAndIncreaseOperatorApproval(address,address,uint256,uint256,uint8,bytes32,bytes32,address,uint256,uint256)" :selector "0x56b29efe"}
  {:contract "filecoinPay" :signature "getAccountInfoIfSettled(address,address)" :selector "0x05f4c536"}
  {:contract "filecoinPay" :signature "getRail(uint256)" :selector "0x22e440b3"}
  {:contract "filecoinPay" :signature "getRailsForPayeeAndToken(address,address,uint256,uint256)" :selector "0x7f7562fa"}
  {:contract "filecoinPay" :signature "getRailsForPayerAndToken(address,address,uint256,uint256)" :selector "0x007b5fd1"}
  {:contract "filecoinPay" :signature "getRateChangeQueueSize(uint256)" :selector "0x356412ae"}
  {:contract "filecoinPay" :signature "increaseOperatorApproval(address,address,uint256,uint256)" :selector "0xa159b1ed"}
  {:contract "filecoinPay" :signature "modifyRailLockup(uint256,uint256,uint256)" :selector "0xde07b8bb"}
  {:contract "filecoinPay" :signature "modifyRailPayment(uint256,uint256,uint256)" :selector "0x97d3ea34"}
  {:contract "filecoinPay" :signature "operatorApprovals(address,address,address)" :selector "0xe3d4c69e"}
  {:contract "filecoinPay" :signature "setOperatorApproval(address,address,bool,uint256,uint256,uint256)" :selector "0x875bc8b6"}
  {:contract "filecoinPay" :signature "settleRail(uint256,uint256)" :selector "0xbcd40bf8"}
  {:contract "filecoinPay" :signature "settleTerminatedRailWithoutValidation(uint256)" :selector "0x4341325c"}
  {:contract "filecoinPay" :signature "terminateRail(uint256)" :selector "0xcbb0bf18"}
  {:contract "filecoinPay" :signature "withdraw(address,uint256)" :selector "0xf3fef3a3"}
  {:contract "filecoinPay" :signature "withdrawTo(address,address,uint256)" :selector "0xc3b35a7e"}
  {:contract "fwss" :signature "UPGRADE_INTERFACE_VERSION()" :selector "0xad3cb1cc"}
  {:contract "fwss" :signature "VERSION()" :selector "0xffa1ad74"}
  {:contract "fwss" :signature "addApprovedProvider(uint256)" :selector "0xa71f9fec"}
  {:contract "fwss" :signature "announcePlannedUpgrade((address,uint96))" :selector "0xbd003827"}
  {:contract "fwss" :signature "configureProvingPeriod(uint64,uint256)" :selector "0xcee4f4c7"}
  {:contract "fwss" :signature "dataSetCreated(uint256,address,bytes)" :selector "0x101c1eab"}
  {:contract "fwss" :signature "dataSetDeleted(uint256,uint256,bytes)" :selector "0x2abd465c"}
  {:contract "fwss" :signature "eip712Domain()" :selector "0x84b0196e"}
  {:contract "fwss" :signature "extsload(bytes32)" :selector "0x1e2eaeaf"}
  {:contract "fwss" :signature "extsloadStruct(bytes32,uint256)" :selector "0x5379a435"}
  {:contract "fwss" :signature "filBeamBeneficiaryAddress()" :selector "0xdd6979bf"}
  {:contract "fwss" :signature "getEffectiveRates()" :selector "0x93124a79"}
  {:contract "fwss" :signature "getProvingPeriodForEpoch(uint256,uint256)" :selector "0x4a1fd7a3"}
  {:contract "fwss" :signature "getServicePrice()" :selector "0x5482bdf9"}
  {:contract "fwss" :signature "initialize(uint64,uint256,address,string,string)" :selector "0x46614302"}
  {:contract "fwss" :signature "migrate(address)" :selector "0xce5494bb"}
  {:contract "fwss" :signature "nextProvingPeriod(uint256,uint256,uint256,bytes)" :selector "0xaa27ebcc"}
  {:contract "fwss" :signature "owner()" :selector "0x8da5cb5b"}
  {:contract "fwss" :signature "paymentsContractAddress()" :selector "0xbc471469"}
  {:contract "fwss" :signature "pdpVerifierAddress()" :selector "0xde4b6b71"}
  {:contract "fwss" :signature "piecesAdded(uint256,uint256,(bytes)[],bytes)" :selector "0xf6814d79"}
  {:contract "fwss" :signature "piecesScheduledRemove(uint256,uint256[],bytes)" :selector "0xe7954aa7"}
  {:contract "fwss" :signature "possessionProven(uint256,uint256,uint256,uint256)" :selector "0x356de02b"}
  {:contract "fwss" :signature "proxiableUUID()" :selector "0x52d1902d"}
  {:contract "fwss" :signature "railTerminated(uint256,address,uint256)" :selector "0xc5153f70"}
  {:contract "fwss" :signature "removeApprovedProvider(uint256,uint256)" :selector "0x5840b83d"}
  {:contract "fwss" :signature "renounceOwnership()" :selector "0x715018a6"}
  {:contract "fwss" :signature "serviceProviderRegistry()" :selector "0x05f892ec"}
  {:contract "fwss" :signature "sessionKeyRegistry()" :selector "0x9f6aa572"}
  {:contract "fwss" :signature "setViewContract(address)" :selector "0x7f6330a1"}
  {:contract "fwss" :signature "settleFilBeamPaymentRails(uint256,uint256,uint256)" :selector "0x3615edff"}
  {:contract "fwss" :signature "storageProviderChanged(uint256,address,address,bytes)" :selector "0x4059b6d7"}
  {:contract "fwss" :signature "terminateCDNService(uint256)" :selector "0x648564c0"}
  {:contract "fwss" :signature "terminateService(uint256)" :selector "0xb997a71e"}
  {:contract "fwss" :signature "terminateService(uint256,bytes)" :selector "0xd0e3c954"}
  {:contract "fwss" :signature "topUpCDNPaymentRails(uint256,uint256,uint256)" :selector "0xeb561d9c"}
  {:contract "fwss" :signature "topUpLifecycleReserve(uint256,uint256)" :selector "0x8f9324dd"}
  {:contract "fwss" :signature "transferFilBeamController(address)" :selector "0x5e786446"}
  {:contract "fwss" :signature "transferOwnership(address)" :selector "0xf2fde38b"}
  {:contract "fwss" :signature "upgradeToAndCall(address,bytes)" :selector "0x4f1ef286"}
  {:contract "fwss" :signature "usdfcTokenAddress()" :selector "0xd39b33ab"}
  {:contract "fwss" :signature "validatePayment(uint256,uint256,uint256,uint256,uint256)" :selector "0x1a7bf46f"}
  {:contract "fwss" :signature "viewContractAddress()" :selector "0x7a9ebc15"}
  {:contract "fwssView" :signature "clientDataSets(address)" :selector "0x7dab7c40"}
  {:contract "fwssView" :signature "clientDataSets(address,uint256,uint256)" :selector "0x1047717c"}
  {:contract "fwssView" :signature "clientNonces(address,uint256)" :selector "0x35b0e3f4"}
  {:contract "fwssView" :signature "filBeamControllerAddress()" :selector "0xd1147eee"}
  {:contract "fwssView" :signature "getAllDataSetMetadata(uint256)" :selector "0xf417c13f"}
  {:contract "fwssView" :signature "getAllPieceMetadata(uint256,uint256)" :selector "0x3c0bd253"}
  {:contract "fwssView" :signature "getApprovedProviders(uint256,uint256)" :selector "0x7709a7f7"}
  {:contract "fwssView" :signature "getApprovedProvidersLength()" :selector "0x4d745000"}
  {:contract "fwssView" :signature "getClientDataSets(address)" :selector "0x967c6f21"}
  {:contract "fwssView" :signature "getClientDataSets(address,uint256,uint256)" :selector "0x3208aa1f"}
  {:contract "fwssView" :signature "getClientDataSetsLength(address)" :selector "0x98a0b04e"}
  {:contract "fwssView" :signature "getCurrentPricingRates()" :selector "0xb5a578fc"}
  {:contract "fwssView" :signature "getDataSet(uint256)" :selector "0xbdaac056"}
  {:contract "fwssView" :signature "getDataSetMetadata(uint256,string)" :selector "0x4dc17df1"}
  {:contract "fwssView" :signature "getDataSetSizeInBytes(uint256)" :selector "0xfe295953"}
  {:contract "fwssView" :signature "getDataSetStatus(uint256)" :selector "0x617285ad"}
  {:contract "fwssView" :signature "getPDPConfig()" :selector "0xea0f9354"}
  {:contract "fwssView" :signature "getPieceMetadata(uint256,uint256,string)" :selector "0x837a7f49"}
  {:contract "fwssView" :signature "getPriceList()" :selector "0xb7029144"}
  {:contract "fwssView" :signature "isProviderApproved(uint256)" :selector "0xb6133b7a"}
  {:contract "fwssView" :signature "nextPDPChallengeWindowStart(uint256)" :selector "0x11d41294"}
  {:contract "fwssView" :signature "nextUpgrade()" :selector "0x315e49ea"}
  {:contract "fwssView" :signature "provenPeriods(uint256,uint256)" :selector "0x698762cb"}
  {:contract "fwssView" :signature "provenThisPeriod(uint256)" :selector "0x7598a1cd"}
  {:contract "fwssView" :signature "provingActivationEpoch(uint256)" :selector "0x725e3216"}
  {:contract "fwssView" :signature "provingDeadline(uint256)" :selector "0x149ac5cc"}
  {:contract "fwssView" :signature "railToDataSet(uint256)" :selector "0x2ad6e6b5"}
  {:contract "fwssView" :signature "service()" :selector "0xd598d4c9"}
  {:contract "fwssView" :signature "serviceCommissionBps()" :selector "0x2afcc1a4"}
  {:contract "usdfc" :signature "allowance(address,address)" :selector "0xdd62ed3e"}
  {:contract "usdfc" :signature "approve(address,uint256)" :selector "0x095ea7b3"}
  {:contract "usdfc" :signature "balanceOf(address)" :selector "0x70a08231"}
  {:contract "usdfc" :signature "decimals()" :selector "0x313ce567"}
  {:contract "usdfc" :signature "name()" :selector "0x06fdde03"}
  {:contract "usdfc" :signature "nonces(address)" :selector "0x7ecebe00"}
  {:contract "usdfc" :signature "symbol()" :selector "0x95d89b41"}
  {:contract "usdfc" :signature "totalSupply()" :selector "0x18160ddd"}
  {:contract "usdfc" :signature "transfer(address,uint256)" :selector "0xa9059cbb"}
  {:contract "usdfc" :signature "transferFrom(address,address,uint256)" :selector "0x23b872dd"}
  {:contract "usdfc" :signature "version()" :selector "0x54fd4d50"}
  {:contract "serviceProviderRegistry" :signature "MAX_CAPABILITIES()" :selector "0x6e36e974"}
  {:contract "serviceProviderRegistry" :signature "MAX_CAPABILITY_KEY_LENGTH()" :selector "0x7f657567"}
  {:contract "serviceProviderRegistry" :signature "MAX_CAPABILITY_VALUE_LENGTH()" :selector "0xdcea1c6f"}
  {:contract "serviceProviderRegistry" :signature "REGISTRATION_FEE()" :selector "0x64b4f751"}
  {:contract "serviceProviderRegistry" :signature "UPGRADE_INTERFACE_VERSION()" :selector "0xad3cb1cc"}
  {:contract "serviceProviderRegistry" :signature "VERSION()" :selector "0xffa1ad74"}
  {:contract "serviceProviderRegistry" :signature "activeProductTypeProviderCount(uint8)" :selector "0x8bdc7747"}
  {:contract "serviceProviderRegistry" :signature "activeProviderCount()" :selector "0xf08bbda0"}
  {:contract "serviceProviderRegistry" :signature "addProduct(uint8,string[],bytes[])" :selector "0x360cc6ac"}
  {:contract "serviceProviderRegistry" :signature "addressToProviderId(address)" :selector "0xe835440e"}
  {:contract "serviceProviderRegistry" :signature "announcePlannedUpgrade((address,uint96))" :selector "0xbd003827"}
  {:contract "serviceProviderRegistry" :signature "eip712Domain()" :selector "0x84b0196e"}
  {:contract "serviceProviderRegistry" :signature "getAllActiveProviders(uint256,uint256)" :selector "0x2f67c065"}
  {:contract "serviceProviderRegistry" :signature "getAllProductCapabilities(uint256,uint8)" :selector "0xa6771f8b"}
  {:contract "serviceProviderRegistry" :signature "getNextProviderId()" :selector "0xd1329d4e"}
  {:contract "serviceProviderRegistry" :signature "getProductCapabilities(uint256,uint8,string[])" :selector "0xa6433240"}
  {:contract "serviceProviderRegistry" :signature "getProvider(uint256)" :selector "0x5c42d079"}
  {:contract "serviceProviderRegistry" :signature "getProviderByAddress(address)" :selector "0x2335bde0"}
  {:contract "serviceProviderRegistry" :signature "getProviderCount()" :selector "0x46ce4175"}
  {:contract "serviceProviderRegistry" :signature "getProviderIdByAddress(address)" :selector "0x93ecb91e"}
  {:contract "serviceProviderRegistry" :signature "getProviderPayee(uint256)" :selector "0x60f4d53a"}
  {:contract "serviceProviderRegistry" :signature "getProviderWithProduct(uint256,uint8)" :selector "0xadd33358"}
  {:contract "serviceProviderRegistry" :signature "getProvidersByIds(uint256[])" :selector "0x5bfe9146"}
  {:contract "serviceProviderRegistry" :signature "getProvidersByProductType(uint8,bool,uint256,uint256)" :selector "0x6ba44226"}
  {:contract "serviceProviderRegistry" :signature "initialize()" :selector "0x8129fc1c"}
  {:contract "serviceProviderRegistry" :signature "isProviderActive(uint256)" :selector "0x83df54a5"}
  {:contract "serviceProviderRegistry" :signature "isRegisteredProvider(address)" :selector "0x51ca236f"}
  {:contract "serviceProviderRegistry" :signature "migrate(string)" :selector "0xc9c5b5b4"}
  {:contract "serviceProviderRegistry" :signature "nextUpgrade()" :selector "0x315e49ea"}
  {:contract "serviceProviderRegistry" :signature "owner()" :selector "0x8da5cb5b"}
  {:contract "serviceProviderRegistry" :signature "productCapabilities(uint256,uint8,string)" :selector "0x4368bafb"}
  {:contract "serviceProviderRegistry" :signature "productTypeProviderCount(uint8)" :selector "0xe459382f"}
  {:contract "serviceProviderRegistry" :signature "providerHasProduct(uint256,uint8)" :selector "0xcde24beb"}
  {:contract "serviceProviderRegistry" :signature "providerProducts(uint256,uint8)" :selector "0x6bf6d74f"}
  {:contract "serviceProviderRegistry" :signature "providers(uint256)" :selector "0x50f3fc81"}
  {:contract "serviceProviderRegistry" :signature "proxiableUUID()" :selector "0x52d1902d"}
  {:contract "serviceProviderRegistry" :signature "registerProvider(address,string,string,uint8,string[],bytes[])" :selector "0x90d270c2"}
  {:contract "serviceProviderRegistry" :signature "removeProduct(uint8)" :selector "0xa9d239b6"}
  {:contract "serviceProviderRegistry" :signature "removeProvider()" :selector "0xb6363b99"}
  {:contract "serviceProviderRegistry" :signature "renounceOwnership()" :selector "0x715018a6"}
  {:contract "serviceProviderRegistry" :signature "transferOwnership(address)" :selector "0xf2fde38b"}
  {:contract "serviceProviderRegistry" :signature "updateProduct(uint8,string[],bytes[])" :selector "0xa128c005"}
  {:contract "serviceProviderRegistry" :signature "updateProviderInfo(string,string)" :selector "0xd1c21b5b"}
  {:contract "serviceProviderRegistry" :signature "upgradeToAndCall(address,bytes)" :selector "0x4f1ef286"}
  {:contract "sessionKeyRegistry" :signature "authorizationExpiry(address,address,bytes32)" :selector "0x9501b2cc"}
  {:contract "sessionKeyRegistry" :signature "login(address,uint256,bytes32[],string)" :selector "0x0848f33f"}
  {:contract "sessionKeyRegistry" :signature "loginAndFund(address,uint256,bytes32[],string)" :selector "0xb318f2e2"}
  {:contract "sessionKeyRegistry" :signature "revoke(address,bytes32[],string)" :selector "0xfd89202e"}
 ])

(def chains
 [
  {:chain :mainnet
   :chain-id 314
   :genesis-timestamp 1598306400
   :contracts
   {
    :usdfc "0x80B98d3aa09ffff255c3ba4A241111Ff1262F045"
    :filecoinPay "0x23b1e018F08BB982348b15a86ee926eEBf7F4DAa"
    :fwss "0x8408502033C418E1bbC97cE9ac48E5528F371A9f"
    :fwssView "0xAD28BBF18A72f728Ed816D07F5a1d7Ec40D68b5e"
    :serviceProviderRegistry "0xf55dDbf63F1b55c3F1D4FA7e339a68AB7b64A5eB"
    :sessionKeyRegistry "0x74FD50525A958aF5d484601E252271f9625231aB"
    :pdp "0xBADd0B92C1c71d02E7d520f64c0876538fa2557F"}}
  {:chain :calibration
   :chain-id 314159
   :genesis-timestamp 1667326380
   :contracts
   {
    :usdfc "0xb3042734b608a1B16e9e86B374A3f3e389B4cDf0"
    :filecoinPay "0x09a0fDc2723fAd1A7b8e3e00eE5DF73841df55a0"
    :fwss "0x02925630df557F957f70E112bA06e50965417CA0"
    :fwssView "0xF4B446171b3677fD2B9b183a9fB76d517365700a"
    :serviceProviderRegistry "0x839e5c9988e4e9977d40708d0094103c0839Ac9D"
    :sessionKeyRegistry "0x518411c2062E119Aaf7A8B12A2eDf9a939347655"
    :pdp "0x85e366Cf9DD2c0aE37E963d9556F5f4718d6417C"}}
 ])

