#!/usr/bin/env nbb
;; Generate test/filecoin/cloud/vectors.cljc from **FilOzone's own SDK** and
;; **viem**.
;;
;; Three separate oracles, none of them this library:
;;
;;   PieceCIDs        @filoz/synapse-core/piece — the implementation the
;;                    service providers and the contracts agree with. A
;;                    commitment scheme that agrees only with itself names
;;                    pieces nobody can prove.
;;   Selectors        viem's toFunctionSelector, from the canonical signature
;;                    strings. There is no keccak in this workspace outside a
;;                    JVM-only namespace, so the constants in `src/` have to
;;                    be checked against something.
;;   Addresses        @filoz/synapse-core/chains — the deployed contracts, as
;;                    published, rather than copied out of a web page.
;;
;;   npm install && nbb testdata/gen_vectors.cljs > test/filecoin/cloud/vectors.cljc
(ns gen-vectors
  (:require ["@filoz/synapse-core/chains" :as chains]
            ["@filoz/synapse-core/piece" :as piece]
            ["viem" :as viem]
            [clojure.string :as str]))

(def payload-sizes
  ;; the boundaries, not round numbers: the 65-byte floor, a full quad (127),
  ;; one past it, the powers of two where the height steps
  [1 2 32 64 65 66 100 126 127 128 129 254 255 256 257 508 1000 1016 1017 4096])

(defn- payload
  "Deterministic, not random — a vector file has to regenerate identically."
  [n]
  (js/Uint8Array.from (clj->js (map #(mod (+ (* % 7) 3) 251) (range n)))))

;; Signatures are read out of the deployed ABIs rather than written down
;; here. A hand-copied signature is how `addPieces` ends up as
;; `(uint256,(bytes)[],bytes)` — plausible, one argument short of the real
;; `(uint256,address,(bytes)[],bytes)`, and a completely different selector.
;; The test then requires every constant in `src/` to appear in this table,
;; so a typo is a missing entry rather than a wrong four bytes.
(def contracts-with-abis
  ["pdp" "filecoinPay" "fwss" "fwssView" "usdfc" "serviceProviderRegistry"
   "sessionKeyRegistry"])

(defn- canonical-type [i]
  (let [t (aget i "type")]
    (if (str/starts-with? t "tuple")
      (str "(" (str/join "," (map canonical-type (array-seq (aget i "components"))))
           ")" (subs t 5))
      t)))

(defn- signature-of [f]
  (str (aget f "name") "("
       (str/join "," (map canonical-type (array-seq (aget f "inputs")))) ")"))

(defn- signatures-of [contract-key]
  (->> (array-seq (aget (aget (aget chains/mainnet "contracts") contract-key) "abi"))
       (filter #(= "function" (aget % "type")))
       (map signature-of)
       distinct
       sort))

(defn- emit-piece [n]
  (-> (piece/calculate (payload n))
      (.then (fn [p]
               (str "  {:size " n
                    "\n   :cid " (pr-str (.toString p))
                    "\n   :height " (.-height p)
                    "\n   :padding " (js/Number (.-padding p))
                    "\n   :padded-size " (js/Number (.-paddedSize p))
                    "\n   :root " (pr-str (viem/bytesToHex (.-root p))) "}")))))

(defn- emit-selector [contract sig]
  (str "  {:contract " (pr-str contract)
       " :signature " (pr-str sig)
       " :selector " (pr-str (viem/toFunctionSelector sig)) "}"))

(defn- emit-chain [label c]
  (let [contracts (.-contracts c)
        entry (fn [k] (str "    " k " "
                           (pr-str (.-address (aget contracts (subs k 1))))))]
    (str "  {:chain " label
         "\n   :chain-id " (.-id c)
         "\n   :genesis-timestamp " (.-genesisTimestamp c)
         "\n   :contracts\n   {\n"
         (str/join "\n" (map entry [":usdfc" ":filecoinPay" ":fwss" ":fwssView"
                                    ":serviceProviderRegistry"
                                    ":sessionKeyRegistry" ":pdp"]))
         "}}")))

(defn -main []
  (-> (js/Promise.all (clj->js (map emit-piece payload-sizes)))
      (.then
       (fn [pieces]
         (println
          (str ";; GENERATED by testdata/gen_vectors.cljs — do not edit by hand.\n"
               ";; PieceCIDs from @filoz/synapse-core/piece; selectors from viem's\n"
               ";; toFunctionSelector; addresses from @filoz/synapse-core/chains.\n"
               ";; None of these come from this library.\n"
               "(ns filecoin.cloud.vectors)\n\n"
               "(def pieces\n [\n" (str/join "\n" (array-seq pieces)) "\n ])\n\n"
               ";; Every function in every deployed ABI, with the selector viem\n"
               ";; derives from its canonical signature. The library's constants\n"
               ";; are checked against this, so a mistyped signature is a missing\n"
               ";; entry rather than four plausible wrong bytes.\n"
               "(def selectors\n [\n"
               (str/join "\n" (mapcat (fn [c] (map #(emit-selector c %) (signatures-of c)))
                                      contracts-with-abis))
               "\n ])\n\n"
               "(def chains\n [\n"
               (str/join "\n" [(emit-chain ":mainnet" chains/mainnet)
                               (emit-chain ":calibration" chains/calibration)])
               "\n ])\n"))))
      (.catch (fn [e] (js/console.error (str e)) (js/process.exit 1)))))

(-main)
